const notificationConsts = {
  apns: [
    {
      identifier: 'WELCOME_OTP_VERIFICATION',
      pushTitle: 'Welcome to SHADOW STAR',
      pushBody: 'Welcome to SHADOW STAR',
      mailSubject: 'OTP Verification',
      mailBody: '',
      fileName: 'welcome-otp-verify',
    },
    {
      identifier: 'WELCOME_MENTOR',
      pushTitle: 'Welcome to SHADOW STAR',
      pushBody: 'Welcome to SHADOW STAR',
      mailSubject: 'Welcome to SHADOW STAR',
      mailBody: '',
      fileName: 'welcome-mentor',
    },
    {
      identifier: 'FORGOT_PASSWORD',
      pushTitle: 'Forgot Password',
      pushBody: 'Forgot Password',
      mailSubject: 'Forgot Password',
      mailBody: '',
      fileName: 'forgot-password',
    },
    {
      identifier: 'SESSION_ACCEPT',
      pushTitle: 'Session Accept',
      pushBody: 'Your session request was accepted',
      mailSubject: '',
      mailBody: '',
      fileName: '',
    },
    {
      identifier: 'SESSION_REJECT',
      pushTitle: 'Session Reject',
      pushBody: 'Your session request was rejected',
      mailSubject: '',
      mailBody: '',
      fileName: '',
    },
    {
      identifier: 'MESSAGE_RECIEVED',
      pushTitle: 'Message Recieved',
      pushBody: 'Your got one message',
      mailSubject: '',
      mailBody: '',
      fileName: '',
    },
    {
      identifier: 'OTP_VERIFICATION',
      pushTitle: '',
      pushBody: '',
      mailSubject: 'OTP Verification',
      mailBody: '',
      fileName: 'welcome-otp-verify',
    },
    {
      identifier: 'MESSGE_RECEIVED',
      pushTitle: 'You have a message',
      pushBody: 'You have a message from {USERNAME}',
      mailSubject: '',
      mailBody: '',
      fileName: '',
    },
    {
      identifier: 'MESSGE_SENT',
      pushTitle: 'You sent a message',
      pushBody: 'You sent a message to {USERNAME}',
      mailSubject: '',
      mailBody: '',
      fileName: '',
    },
    {
      identifier: 'PRE_SESSION_NOTIFY',
      pushTitle: 'Pre-session notify',
      pushBody: 'Your session will be start in next {MINUTES} minutes',
      mailSubject: 'Pre-session notify',
      mailBody: '',
      fileName: 'pre-session-notify',
    },
    {
      identifier: 'SESSION_STARTED',
      pushTitle: 'Session started',
      pushBody: 'Your session with {NAME} has started',
      mailSubject: '',
      mailBody: '',
      fileName: '',
    },
    {
      identifier: 'UPDATE_IN_ACTIVE_SESSION',
      pushTitle: 'Auto cancel session',
      pushBody: 'Your session was cancelled due to no action from the mentor',
      mailSubject: '',
      mailBody: '',
      fileName: '',
    },
    {
      identifier: 'STOP_EXPIRED_SESSION',
      pushTitle: 'Auto stop session',
      pushBody: 'Your session has stopped because the session time has expired',
      mailSubject: '',
      mailBody: '',
      fileName: '',
    },
    {
      identifier: 'SESSION_REQUEST',
      pushTitle: 'Session Request',
      pushBody: 'You have one session request',
      mailSubject: '',
      mailBody: '',
      fileName: '',
    },
    {
      identifier: 'MENTOR_COST_CHANGED',
      pushTitle: 'Mentor Cost Changed',
      pushBody: 'Mentor Cost Changed',
      mailSubject: 'Mentor Cost Changed',
      mailBody: '',
      fileName: 'mentor-cost-changed',
    },
    {
      identifier: 'MENTOR_PASSWORD_CHANGED',
      pushTitle: 'Your password has been changed by Admin',
      pushBody: 'Your password has been changed by Admin',
      mailSubject: 'Password Changed',
      mailBody: '',
      fileName: 'mentor-password-change',
    },
    {
      identifier: 'NEW_SESSION_BOOKED',
      pushTitle: 'New Session Booked',
      pushBody: 'New Session Booked',
      mailSubject: 'New Session Booked',
      mailBody: '',
      fileName: 'new-session-booked',
    },
    {
      identifier: 'SESSION_CANCELLED',
      pushTitle: 'A session has been cancelled',
      pushBody: 'A session has been cancelled by {RESPONSIBLEPERSON}',
      mailSubject: 'A session has been cancelled',
      mailBody: '',
      fileName: 'session-cancelled',
    },
    {
      identifier: 'GOT_PROMO_CODE',
      pushTitle: 'You got a promo code',
      pushBody: 'Your promo code is {PROMO_CODE}',
      mailSubject: 'You got a promo code',
      mailBody: '',
      fileName: 'got-promo-code',
    },
  ],
};

module.exports = notificationConsts;
  
